version: '2'
services:
  consul:
    image: consul:1.6
    ports:
    - '8300:8300'
    - '8500:8500'
    - '8600:8600'
    volumes:
    - ./data/consul:/data
    - ./config:/config
    command: agent -server -data-dir=/data -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect=1 -ui
  postgresql:
    image: postgres:11
    ports:
    - '5432:5432'
    volumes:
    - ./data/pgsql:/var/lib/postgresql/data
    env_file:
    - ./envs/common.env
  redis:
    image: redis:5.0-alpine
    ports:
    - '6379:6379'
  router-confd:
    image: wazopbx/wazo-router-confd:latest
    ports:
    - 8000:8000
    env_file:
    - ./envs/common.env
    command: "wazo-router-confd --host 0.0.0.0 --port 8000 --advertise-host router-confd --advertise-port 8000 --consul-uri http://consul:8500 --database-uri postgresql://wazo:wazo@postgresql:5432/wazo --redis-uri redis://redis"
  rtpe:
    image: wazopbx/wazo-rtpe:latest
    env_file:
    - ./envs/common.env
    - ./envs/rtpe.env
    environment:
      LISTEN_NG: 22222
      SUBSCRIBE_KEYSPACE: 2
  rtpe_secondary:
    image: wazopbx/wazo-rtpe:latest
    env_file:
    - ./envs/common.env
    - ./envs/rtpe.env
    environment:
      LISTEN_NG: 22222
      SUBSCRIBE_KEYSPACE: 1
  sbc:
    image: 'wazopbx/wazo-c4-sbc:latest'
    env_file:
    - ./envs/common.env
    - ./envs/sbc.env
    ports:
    - "5060:5060/udp"
    environment:
      LISTEN_ADVERTISE: sbc:5060
      ALIAS: sbc_secondary:5060
      DMQ_NOTIFICATION_ADDRESS: "sip:sbc_secondary:5062"
  sbc_secondary:
    image: 'wazopbx/wazo-c4-sbc:latest'
    env_file:
    - ./envs/common.env
    - ./envs/sbc.env
    environment:
      LISTEN_ADVERTISE: sbc_secondary:5060
      ALIAS: sbc:5060
      DMQ_NOTIFICATION_ADDRESS: "sip:sbc:5062"
  router:
    image: 'wazopbx/wazo-c4-router:latest'
    env_file:
    - ./envs/common.env
    - ./envs/router.env
    environment:
      LISTEN_ADVERTISE: router:5061
      ALIAS: router_secondary:5061
      DMQ_NOTIFICATION_ADDRESS: "sip:router_secondary:5062"
      DISPATCHER_WEIGHT: 10
  router_secondary:
    image: 'wazopbx/wazo-c4-router:latest'
    env_file:
    - ./envs/common.env
    - ./envs/router.env
    environment:
      LISTEN_ADVERTISE: router_secondary:5061
      ALIAS: router:5061
      DMQ_NOTIFICATION_ADDRESS: "sip:router:5062"
      DISPATCHER_WEIGHT: 5
  carrier:
    image: 'wazopbx/wazo-c4-carrier:latest'
    entrypoint: 'sipp -sf /scenarios/uas.xml'
  wazo-tester:
    image: 'wazopbx/wazo-tester:latest'
    environment:
      API_ENDPOINT: http://router-confd:8000
      TARGET: sbc:5060
    volumes:
    - "./tests/:/tests/"
    command: sh -c "while true; do sleep 30; done;"
