version: '2'
services:
  consul:
    image: consul:1.6
    ports:
    - '8300:8300'
    - '8500:8500'
    - '8600:8600'
    volumes:
    - ./data/consul:/data
    - ./config:/config
    command: agent -server -data-dir=/data -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect=1 -ui
  postgresql:
    image: postgres:11
    ports:
    - '5432:5432'
    volumes:
    - ./data/pgsql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: wazo
      POSTGRES_PASSWORD: wazo
      POSTGRES_DB: wazo
  redis:
    image: redis:5.0-alpine
  router-confd:
    image: wazopbx/wazo-router-confd:latest
    ports:
    - 8000:8000
    command: sh -c "date
      && wait-for -t 60 postgresql:5432
      && wait-for -t 60 consul:8500
      && sleep 15
      && wazo-router-confd --host 0.0.0.0 --port 8000 --consul-uri http://consul:8500 --database-uri postgresql://wazo:wazo@postgresql:5432/wazo
      && date"
  rtpe:
    image: wazopbx/wazo-rtpe:latest
    env_file:
    - ./envs/common.env
    environment:
      LISTEN_NG: 22222
      SUBSCRIBE_KEYSPACE: 2
    command: sh -c "date
      && wait-for -t 120 router-confd:8000
      && wait-for -t 120 consul:8500
      && sleep 2
      && /docker-entrypoint.sh
      && date"
  rtpe_secondary:
    image: wazopbx/wazo-rtpe:latest
    env_file:
    - ./envs/common.env
    environment:
      LISTEN_NG: 22222
      SUBSCRIBE_KEYSPACE: 1
    command: sh -c "date
      && wait-for -t 60 router-confd:8000
      && wait-for -t 60 consul:8500
      && sleep 2
      && /docker-entrypoint.sh
      && date"
  sbc:
    image: 'wazopbx/wazo-c4-sbc:latest'
    ports:
    - "5060:5060/udp"
    env_file:
    - ./envs/common.env
    - ./envs/sbc.env
    environment:
      DMQ_NOTIFICATION_ADDRESS: "sip:sbc_secondary:5062"
    command: sh -c "date
      && wait-for -t 60 router-confd:8000
      && wait-for -t 60 consul:8500
      && sleep 2
      && /docker-entrypoint.sh
      && date"
  sbc_secondary:
    image: 'wazopbx/wazo-c4-sbc:latest'
    env_file:
    - ./envs/common.env
    - ./envs/sbc.env
    environment:
      DMQ_NOTIFICATION_ADDRESS: "sip:sbc:5062"
    command: sh -c "date
      && wait-for -t 60 router-confd:8000
      && wait-for -t 60 consul:8500
      && sleep 2
      && /docker-entrypoint.sh
      && date"
  router:
    image: 'wazopbx/wazo-c4-router:latest'
    ports:
    - "5061:5061/udp"
    env_file:
    - ./envs/common.env
    - ./envs/router.env
    environment:
      LISTEN_ADVERTISE: router:5061
      ALIAS: router_secondary:5061
      DMQ_NOTIFICATION_ADDRESS: "sip:router_secondary:5062"
    command: sh -c "date
      && wait-for -t 60 router-confd:8000
      && wait-for -t 60 consul:8500
      && sleep 2
      && /docker-entrypoint.sh
      && date"
  router_secondary:
    image: 'wazopbx/wazo-c4-router:latest'
    env_file:
    - ./envs/common.env
    - ./envs/router.env
    environment:
      LISTEN_ADVERTISE: router_secondary:5061
      ALIAS: router:5061
      DMQ_NOTIFICATION_ADDRESS: "sip:router:5062"
    command: sh -c "date
      && wait-for -t 60 router-confd:8000
      && wait-for -t 60 consul:8500
      && sleep 2
      && /docker-entrypoint.sh
      && date"
  carrier:
    image: 'wazopbx/wazo-c4-carrier:latest'
    entrypoint: 'sipp -sf /scenarios/uas.xml'
  wazo-tester:
    image: 'wazopbx/wazo-tester:latest'
    environment:
      API_ENDPOINT: http://router-confd:8000
      TARGET: sbc:5060
    volumes:
    - "./tests/:/tests/"
    command: sh -c "while true; do sleep 30; done;"
