version: '2'
services:
  consul:
    command: agent -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect=1 -ui
  postgresql:
    volumes:
    - "./data/pgsql:/var/lib/postgresql/data"
  sbc:
    volumes:
    - "../wazo-c4-router/kamailio/kamailio-sbc.cfg:/etc/kamailio/kamailio.cfg"
    - "../wazo-c4-router/kamailio/xhttp-sbc.cfg:/etc/kamailio/xhttp-sbc.cfg"
    - "../wazo-c4-router/docker-entrypoint-sbc.sh:/docker-entrypoint.sh"
    - "../wazo-c4-router/consul-templates/sbc:/consul-templates/sbc"
    - "../wazo-c4-router/supervisord/supervisord-sbc.conf:/etc/supervisor/conf.d/supervisord.conf"
  sbc_secondary:
    volumes:
    - "../wazo-c4-router/kamailio/kamailio-sbc.cfg:/etc/kamailio/kamailio.cfg"
    - "../wazo-c4-router/kamailio/xhttp-sbc.cfg:/etc/kamailio/xhttp-sbc.cfg"
    - "../wazo-c4-router/docker-entrypoint-sbc.sh:/docker-entrypoint.sh"
    - "../wazo-c4-router/consul-templates/sbc:/consul-templates/sbc"
    - "../wazo-c4-router/supervisord/supervisord-sbc.conf:/etc/supervisor/conf.d/supervisord.conf"
  router:
    volumes:
    - "../wazo-c4-router/kamailio/kamailio-router.cfg:/etc/kamailio/kamailio.cfg"
    - "../wazo-c4-router/kamailio/routing.cfg:/etc/kamailio/routing.cfg"
    - "../wazo-c4-router/kamailio/cdrs.cfg:/etc/kamailio/cdrs.cfg"
    - "../wazo-c4-router/kamailio/xhttp-router.cfg:/etc/kamailio/xhttp-router.cfg"
    - "../wazo-c4-router/docker-entrypoint-router.sh:/docker-entrypoint-router.sh"
    - "../wazo-c4-router/consul-templates/router:/consul-templates/router"
    - "../wazo-c4-router/supervisord/supervisord-router.conf:/etc/supervisor/conf.d/supervisord.conf"
  router_secondary:
    volumes:
    - "../wazo-c4-router/kamailio/kamailio-router.cfg:/etc/kamailio/kamailio.cfg"
    - "../wazo-c4-router/kamailio/routing.cfg:/etc/kamailio/routing.cfg"
    - "../wazo-c4-router/kamailio/cdrs.cfg:/etc/kamailio/cdrs.cfg"
    - "../wazo-c4-router/kamailio/xhttp-router.cfg:/etc/kamailio/xhttp-router.cfg"
    - "../wazo-c4-router/docker-entrypoint-router.sh:/docker-entrypoint-router.sh"
    - "../wazo-c4-router/consul-templates/router:/consul-templates/router"
    - "../wazo-c4-router/supervisord/supervisord-router.conf:/etc/supervisor/conf.d/supervisord.conf"
  carrier:
    volumes:
    - "../wazo-c4-carrier/sipp/scenarios/:/scenarios/"
  wazo-tester:
    volumes:
    - "./tests/:/tests/"
