version: '2'
services:
  consul:
    image: consul:1.6
    ports:
    - '8300:8300'
    - '8500:8500'
    - '8600:8600'
    volumes:
    - ./data/consul:/data
    - ./config:/config
    command: agent -server -data-dir=/data -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect=1 -ui
  postgresql:
    image: postgres:11
    ports:
    - '5432:5432'
    volumes:
    - ./data/pgsql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: wazo
      POSTGRES_PASSWORD: wazo
      POSTGRES_DB: wazo
  redis:
    image: redis:5.0-alpine
  router-confd:
    image: wazopbx/wazo-router-confd:latest
    ports:
    - 8000:8000
    command: sh -c "
      date
      && wait-for -t 60 postgresql:5432
      && wait-for -t 60 consul:8500
      && sleep 15
      && wazo-router-confd --host 0.0.0.0 --port 8000 --consul-uri http://consul:8500 --database-uri postgresql://wazo:wazo@postgresql:5432/wazo
      && date"
  rtpe:
    image: wazopbx/wazo-rtpe:latest
    environment:
      LISTEN_NG: 22222
      REDIS: redis:6379/1
      SUBSCRIBE_KEYSPACE: 2
  rtpe_secondary:
    image: wazopbx/wazo-rtpe:latest
    environment:
      LISTEN_NG: 22222
      REDIS: redis:6379/2
      SUBSCRIBE_KEYSPACE: 1
  sbc:
    image: 'wazopbx/wazo-c4-sbc:latest'
    ports:
    - "5060:5060/udp"
    environment:
      TESTING: 1
      LISTEN: udp:eth0:5060
      DISPATCHER_LIST: >-
        # setid(int) destination(sip uri) flags(int,opt) priority(int,opt) attributes(str,opt)\n
        1 sip:router:5061 16 10\n
        1 sip:router_secondary:5061 16 5
      WITH_DMQ: 1
      DISPATCHER_ALG: 8
      DMQ_PORT: 5062
      DMQ_LISTEN: "udp:eth0:5062"
      DMQ_SERVER_ADDRESS: "sip:eth0:5062"
      DMQ_NOTIFICATION_ADDRESS: "sip:sbc_secondary:5062"
    command: sh -c "
      date
      && wait-for -t 60 router-confd:8000
      && /docker-entrypoint.sh
      && sleep 5000
      && date"
  sbc_secondary:
    image: 'wazopbx/wazo-c4-sbc:latest'
    environment:
      TESTING: 1
      LISTEN: udp:eth0:5060
      DISPATCHER_LIST: >-
        # setid(int) destination(sip uri) flags(int,opt) priority(int,opt) attributes(str,opt)\n
        1 sip:router:5061 0 10\n
        1 sip:router_secondary:5061 0 5
      WITH_DMQ: 1
      DISPATCHER_ALG: 8
      DMQ_PORT: 5062
      DMQ_LISTEN: "udp:eth0:5062"
      DMQ_SERVER_ADDRESS: "sip:eth0:5062"
      DMQ_NOTIFICATION_ADDRESS: "sip:sbc:5062"
    command: sh -c "
      date
      && wait-for -t 60 router-confd:8000
      && /docker-entrypoint.sh
      && sleep 5000
      && date"
  router:
    image: 'wazopbx/wazo-c4-router:latest'
    ports:
    - "5061:5061/udp"
    environment:
      TESTING: 1
      ROUTER_AUTH_SECRET: "ROUTER_AUTH_SHARED_SECRET"
      RTPENGINE_LIST: udp:rtpe:22222=1 udp:rtpe_secondary:22222=1
      HTTP_API_ROUTING_ENDPOINT: http://router-confd:8000/kamailio/routing
      HTTP_API_CDR_ENDPOINT: http://router-confd:8000/kamailio/cdr
      HTTP_API_DBTEXT_UACREG_ENDPOINT: http://router-confd:8000/kamailio/dbtext/uacreg
      HTTP_API_TIMEOUT: 5000
      LISTEN: udp:eth0:5061
      LISTEN_ADVERTISE: router:5061
      ALIAS: router_secondary:5061
      WITH_DMQ: 1
      DMQ_PORT: 5062
      DMQ_LISTEN: "udp:eth0:5062"
      DMQ_SERVER_ADDRESS: "sip:eth0:5062"
      DMQ_NOTIFICATION_ADDRESS: "sip:router_secondary:5062"
  router_secondary:
    image: 'wazopbx/wazo-c4-router:latest'
    environment:
      TESTING: 1
      ROUTER_AUTH_SECRET: "ROUTER_AUTH_SHARED_SECRET"
      RTPENGINE_LIST: udp:rtpe:22222=1 udp:rtpe_secondary:22222=1
      HTTP_API_ROUTING_ENDPOINT: http://router-confd:8000/kamailio/routing
      HTTP_API_CDR_ENDPOINT: http://router-confd:8000/kamailio/cdr
      HTTP_API_DBTEXT_UACREG_ENDPOINT: http://router-confd:8000/kamailio/dbtext/uacreg
      HTTP_API_TIMEOUT: 5000
      LISTEN: udp:eth0:5061
      LISTEN_ADVERTISE: router_secondary:5061
      ALIAS: router:5061
      WITH_DMQ: 1
      DMQ_PORT: 5062
      DMQ_LISTEN: "udp:eth0:5062"
      DMQ_SERVER_ADDRESS: "sip:eth0:5062"
      DMQ_NOTIFICATION_ADDRESS: "sip:router:5062"
  carrier:
    image: 'wazopbx/wazo-c4-carrier:latest'
    entrypoint: 'sipp -sf /scenarios/uas.xml'
  wazo-tester:
    image: 'wazopbx/wazo-tester:latest'
    environment:
      API_ENDPOINT: http://router-confd:8000
      TARGET: sbc:5060
    volumes:
    - "./tests/:/tests/"
    command: sh -c "while true; do sleep 30; done;"
